server:
  port: 8100
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/online_store_dev
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 465
    username: psevdo.intellectual02@gmail.com
    password: ${emailPassword}
    protocol: smtps
jwt:
  secret: qwertyuiopasdfghjklzxcvbnmqwertyuioh
  expiration: 86400
  time:
    delete-tokens: 60000
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: C:\Users\maxim\Repozinory\onlineStore\online-store\auth-server\src\main\resources\spring.log
api:
  google:
    checkToken: https://www.googleapis.com/oauth2/v1/tokeninfo
needSynch: true

cloudinary:
  cloud-name: maksim
  api-key: 144789595384786
  api-secret: HsH0z_k-HBvKxMGAuXWU_f9H7Jg

product:
  catalog:
    size: 10

auction:
  days: 3

